#!/bin/bash -e

#top level driver that sets up and invokes JackTokenizer and CompilationEngine

jack="$1"
path="$(dirname $jack)"
filename="$(basename $jack)"
tokens="$(echo $filename | cut -d "." -f 1)_T.xml"
core_name=$(echo $filename | cut -d "." -f 1)

node JackTokenizer.js $jack

#sed-fu to make parsing of tokensizer output easier

sed -e 's/[^<]*<\([^>]*\)> \([^<]*\) <[^>]*>/"\1" "\2"/g' -e '/<\/*tokens>/d' "${path}/${tokens}" > "${path}/tokens"

#invoke compilation engine

node --stack_size=8000 CompilationEngine.js "${path}/tokens" "$core_name"
